- _target_: src.metrics.NDCGMetric
  k: 20
- _target_: src.metrics.NDCGMetric
  k: 10
- _target_: src.metrics.NDCGMetric
  k: 5
- _target_: src.metrics.RecallMetric
  k: 20
- _target_: src.metrics.RecallMetric
  k: 10
- _target_: src.metrics.RecallMetric
  k: 5
- _target_: src.metrics.CoverageMetric
  k: 20
- _target_: src.metrics.CoverageMetric
  k: 10
- _target_: src.metrics.CoverageMetric
  k: 5
