_target_: src.models.joint_sasrec_ultragcn.JointSASRecUltraGCN
name: mix_model
seed: 42
device: cuda

hidden_size: 128 
lr: 1e-3
lambda_reg: 1e-4
n_epochs: 1000

lambda_sas: 1.0
lambda_ultra: 1

seq_len: 200
num_blocks: 3
num_heads: 2
dropout: 0.2

s: 1024
alpha: 1.0
beta: 16.0
bucket_size_y: 256
mix_x: true

batch_size_sas: 256
log_step: 100

embedding_dim: 128
w1: 1e-7
w2: 1.0
w3: 1e-7
w4: 1.0

negative_weight: 200
negative_num: 200
gamma: 1e-3
num_neighbors: 10