- name: rank
  type: int
  low: 32
  high: 256
  step: 32
- name: batch_size
  type: int
  low: 512
  high: 2048
  step: 256
- name: learning_rate
  type: float
  log: true
  low: 5e-4
  high: 0.1
- name: regularization
  type: float
  log: true
  low: 1e-4
  high: 0.1
- name: n_layers
  type: int
  low: 2
  high: 4
  step: 1
- name: edge_dropout
  type: float
  log: false
  low: 0.0
  high: 0.4
- name: lambda_geo
  type: int
  low: 256
  high: 1024
  step: 128
- name: eta
  type: int
  low: 1
  high: 3
  step: 1
- name: resample_every_factor
  type: float
  log: false
  low: 0.2
  high: 1.5
