- name: embedding_dim
  type: int
  low: 32
  high: 512
  step: 32
- name: w1
  type: float
  log: true
  low: 1e-8
  high: 1
- name: w2
  type: float
  log: true
  low: 1e-8
  high: 1
- name: w3
  type: float
  log: true
  low: 1e-8
  high: 1
- name: w4
  type: float
  log: true
  low: 1e-8
  high: 1
- name: negative_weight
  type: int
  low: 50
  high: 500
  step: 50
- name: negative_num
  type: int
  low: 50
  high: 500
  step: 50
- name: gamma
  type: float
  log: true
  low: 1e-4
  high: 1
- name: lambda_reg
  type: float
  log: true
  low: 1e-5
  high: 1e-3
- name: lr
  type: float
  log: true
  low: 1e-4
  high: 1e-2
